---
name: Deploy security.txt to Azure 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Timestamp security.txt
        run: ./timestamp.sh

      - name: Deploy terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Terraform version
        run: terraform -version

        # Terraform
      # - name: Run terraform
      #   env:
      #     ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      #   run: cd terraform/; terraform init; terraform apply -auto-approve