---
name: Deploy security.txt to Azure 

on:
  push:
    branches:
      - main
    paths:
      - '**.txt'
      - 'index.html'
      - 'terraform/**'
      - '.github/workflows/deploy-to-azure.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Timestamp security.txt
        run: ./timestamp.sh

      - name: Deploy terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4
          terraform_wrapper: false

      - name: Terraform version
        run: terraform -version

        # Terraform
      # - name: Run terraform
      #   env:
      #     ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      #   run: cd terraform/; terraform init; terraform apply -auto-approve

      - name: Get terraform output values
        id: tf-output
        run: |
          echo "SG_WEB_HOST=$(terraform output -raw storage_account_primary_web_host)" >> $GITHUB_OUTPUT
      
      - name: Availability test
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" https://${{ steps.tf-output.outputs.SG_WEB_HOST }}/.well-known/security.txt)
          
          if [ $status_code == 200 ]
          then
            echo "Security.txt successfully deployed to https://${{ steps.tf-output.outputs.SG_WEB_HOST }}"
          else
            echo "Error deploying to https://${{ steps.tf-output.outputs.SG_WEB_HOST }}, status code returned: $status_code"
            exit 1
          fi